"""
LogIQ — Insurance / regulator PDF.

Wraps the standard verdict PDF with extra metadata required for
insurance claims (operator info, drone serial, incident classification)
and CAAB-compliant reporting.
"""
from __future__ import annotations

from io import BytesIO
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas


def build_insurance_pdf(verdict: dict, claim: dict | None = None) -> bytes:
    """Generate an insurance-claim-ready PDF.

    Args:
        verdict: standard LogIQ verdict dict
        claim: optional {operator_name, operator_id, drone_serial, location,
                          incident_description, claim_amount_bdt}
    """
    claim = claim or {}
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    W, H = A4
    margin = 18 * mm

    flight = verdict.get("flight", {})

    # === HEADER ===
    c.setFillColor(colors.HexColor("#1e3a8a"))
    c.rect(0, H - 30 * mm, W, 30 * mm, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 20)
    c.drawString(margin, H - 14 * mm, "Flight Incident Report")
    c.setFont("Helvetica", 9)
    c.drawString(margin, H - 19 * mm, "Generated by LogIQ — automated UAV flight log analysis")
    c.drawString(margin, H - 23 * mm, f"Report date: {datetime.now().strftime('%Y-%m-%d %H:%M')} UTC+6")
    c.drawRightString(W - margin, H - 14 * mm, "INSURANCE CLAIM / REGULATORY")
    c.drawRightString(W - margin, H - 19 * mm, "Document type: Forensic flight analysis")

    y = H - 40 * mm

    def section(title: str):
        nonlocal y
        c.setFillColor(colors.HexColor("#1e3a8a"))
        c.rect(margin, y, W - 2 * margin, 6 * mm, fill=1, stroke=0)
        c.setFillColor(colors.white)
        c.setFont("Helvetica-Bold", 10)
        c.drawString(margin + 4, y + 1.5 * mm, title)
        y -= 9 * mm
        c.setFillColor(colors.HexColor("#1f2937"))

    def row(label: str, value: str):
        nonlocal y
        c.setFont("Helvetica-Bold", 10)
        c.drawString(margin + 4, y, label + ":")
        c.setFont("Helvetica", 10)
        c.drawString(margin + 60 * mm, y, str(value or "—"))
        y -= 6 * mm

    section("1. Operator information")
    row("Operator name", claim.get("operator_name", "Zasif Bin Islam"))
    row("Operator ID / NID", claim.get("operator_id", "TBD"))
    row("Drone serial", claim.get("drone_serial", flight.get("file_name", "—")))
    row("Airframe class", flight.get("bucket", "—"))
    row("Firmware", (flight.get("firmware") or "")[:60])

    section("2. Incident details")
    row("Date of incident", (flight.get("flown_at") or "—")[:19])
    row("Flight duration", f"{flight.get('duration_s', '—')} s")
    row("Location", claim.get("location", "GPS coordinates from log"))
    row("Operator description", claim.get("incident_description", "Automatic from log analysis"))

    section("3. Forensic analysis")
    row("Overall health score", f"{verdict.get('overall_score')}/100  ({verdict.get('overall_status', '').upper()})")
    row("Verdict", verdict.get("summary_en", "—")[:80])

    y -= 2 * mm
    c.setFont("Helvetica-Bold", 10)
    c.drawString(margin + 4, y, "Per-category breakdown:")
    y -= 6 * mm
    c.setFont("Helvetica", 10)
    for cat in verdict.get("categories", []):
        c.drawString(margin + 8, y, f"{cat.get('icon','')} {cat.get('name_en')}: {cat.get('score')}/100 ({cat.get('status', '').upper()})")
        y -= 5 * mm
        for issue in (cat.get("issues_en") or [])[:2]:
            c.setFont("Helvetica-Oblique", 9)
            c.drawString(margin + 14, y, "- " + issue[:90])
            c.setFont("Helvetica", 10)
            y -= 4 * mm
        if y < 50 * mm:
            c.showPage(); y = H - margin

    if y < 70 * mm: c.showPage(); y = H - margin

    section("4. Recommended actions / repair items")
    for i, a in enumerate(verdict.get("actions", []), 1):
        c.drawString(margin + 4, y, f"{i}. {a.get('en', '')[:100]}")
        y -= 5 * mm
        if y < 30 * mm: c.showPage(); y = H - margin

    if y < 40 * mm: c.showPage(); y = H - margin
    section("5. Claim / declaration")
    row("Claimed amount (BDT)", str(claim.get("claim_amount_bdt", "TBD")))

    y -= 6 * mm
    c.setFont("Helvetica", 9)
    c.drawString(margin + 4, y, "I declare the above information is accurate and the log file is the original.")
    y -= 10 * mm
    c.line(margin + 4, y, margin + 60 * mm, y)
    y -= 4 * mm
    c.drawString(margin + 4, y, "Operator signature & date")

    # Footer
    c.setFillColor(colors.HexColor("#9ca3af"))
    c.setFont("Helvetica", 7)
    c.drawString(margin, 10 * mm, "LogIQ insurance PDF — automated forensic UAV analysis. For full log access, request the .bin file.")
    c.drawRightString(W - margin, 10 * mm, f"Flight ID: {flight.get('id', '—')[:8]}")

    c.save()
    return buf.getvalue()
