"""
LogIQ — Insurance / regulator PDF.

Generates a claim-ready PDF with operator info, incident classification,
and forensic breakdown. Layout uses a strict Y-cursor with per-section
overflow protection so content never bleeds into the next section bar.
"""
from __future__ import annotations

from io import BytesIO
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas


COL_PRIMARY = colors.HexColor("#1e3a8a")
COL_TEXT = colors.HexColor("#1f2937")
COL_MUTED = colors.HexColor("#6b7280")
COL_LIGHT = colors.HexColor("#9ca3af")


def build_insurance_pdf(verdict: dict, claim: dict | None = None) -> bytes:
    claim = claim or {}
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    W, H = A4
    margin = 18 * mm

    flight = verdict.get("flight", {})

    # ---------- helpers ----------
    state = {"y": H - margin}
    LINE_H = 5.5 * mm
    SECTION_H = 8 * mm
    SECTION_GAP_AFTER = 4 * mm

    def need(min_space: float):
        """Ensure at least min_space remains; else page break."""
        if state["y"] - min_space < margin + 12 * mm:
            footer()
            c.showPage()
            state["y"] = H - margin

    def footer():
        c.setFillColor(COL_LIGHT)
        c.setFont("Helvetica", 7)
        c.drawString(margin, 10 * mm, "LogIQ insurance PDF — automated forensic UAV analysis · For full log access, request the .bin file.")
        c.drawRightString(W - margin, 10 * mm, f"Flight ID: {flight.get('id', '—')[:8]}")

    def section(title: str):
        need(SECTION_H + LINE_H * 3)
        c.setFillColor(COL_PRIMARY)
        c.rect(margin, state["y"] - SECTION_H, W - 2 * margin, SECTION_H, fill=1, stroke=0)
        c.setFillColor(colors.white)
        c.setFont("Helvetica-Bold", 10)
        c.drawString(margin + 4, state["y"] - SECTION_H + 2.5 * mm, title)
        state["y"] -= SECTION_H + SECTION_GAP_AFTER
        c.setFillColor(COL_TEXT)

    def row(label: str, value: str, label_width_mm: float = 52):
        need(LINE_H + 2 * mm)
        c.setFont("Helvetica-Bold", 9.5)
        c.drawString(margin + 4, state["y"], label + ":")
        c.setFont("Helvetica", 9.5)
        v = str(value or "—")
        # Truncate so it never wraps past the right margin
        max_width = W - margin - (margin + 4 + label_width_mm * mm) - 2
        if c.stringWidth(v, "Helvetica", 9.5) > max_width:
            while v and c.stringWidth(v + "…", "Helvetica", 9.5) > max_width:
                v = v[:-1]
            v += "…"
        c.drawString(margin + 4 + label_width_mm * mm, state["y"], v)
        state["y"] -= LINE_H

    def para(text: str, font_size: float = 9.5, indent_mm: float = 8, italic: bool = False):
        font = "Helvetica-Oblique" if italic else "Helvetica"
        c.setFont(font, font_size)
        words = text.split()
        line = ""
        max_w = W - 2 * margin - indent_mm * mm
        while words:
            candidate = (line + " " + words[0]).strip()
            if c.stringWidth(candidate, font, font_size) <= max_w:
                line = candidate
                words.pop(0)
            else:
                need(LINE_H + 1 * mm)
                c.drawString(margin + indent_mm * mm, state["y"], line)
                state["y"] -= font_size * 1.35
                line = ""
        if line:
            need(LINE_H + 1 * mm)
            c.drawString(margin + indent_mm * mm, state["y"], line)
            state["y"] -= font_size * 1.35

    def spacer(h_mm: float = 2):
        state["y"] -= h_mm * mm

    # ---------- HEADER ----------
    c.setFillColor(COL_PRIMARY)
    c.rect(0, H - 30 * mm, W, 30 * mm, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 20)
    c.drawString(margin, H - 14 * mm, "Flight Incident Report")
    c.setFont("Helvetica", 9)
    c.drawString(margin, H - 19.5 * mm, "Generated by LogIQ — automated UAV flight log analysis")
    c.drawString(margin, H - 24 * mm, f"Report date: {datetime.now().strftime('%Y-%m-%d %H:%M')} UTC+6")
    c.drawRightString(W - margin, H - 14 * mm, "INSURANCE CLAIM / REGULATORY")
    c.drawRightString(W - margin, H - 19.5 * mm, "Document type: Forensic flight analysis")

    state["y"] = H - 38 * mm

    # ---------- 1. OPERATOR ----------
    section("1. Operator information")
    row("Operator name",    claim.get("operator_name", "Zasif Bin Islam"))
    row("Operator ID / NID", claim.get("operator_id", "TBD"))
    row("Drone serial",     claim.get("drone_serial", flight.get("file_name", "—")))
    row("Airframe class",   flight.get("bucket", "—"))
    row("Firmware",         (flight.get("firmware") or ""))
    spacer(3)

    # ---------- 2. INCIDENT ----------
    section("2. Incident details")
    row("Date of incident", (flight.get("flown_at") or "—")[:19])
    row("Flight duration",  f"{flight.get('duration_s', '—')} s")
    row("Location",         claim.get("location", "GPS coordinates from log"))
    row("Operator description", claim.get("incident_description", "Automatic from log analysis"))
    spacer(3)

    # ---------- 3. FORENSIC ----------
    section("3. Forensic analysis")
    row("Overall health score", f"{verdict.get('overall_score')}/100 ({verdict.get('overall_status', '').upper()})")
    row("Verdict", verdict.get("summary_en", "—"))

    spacer(2)
    c.setFont("Helvetica-Bold", 9.5)
    need(LINE_H)
    c.drawString(margin + 4, state["y"], "Per-category breakdown:")
    state["y"] -= LINE_H

    for cat in verdict.get("categories", []):
        need(LINE_H * 2)
        c.setFont("Helvetica-Bold", 9.5)
        title = f"{cat.get('icon','')} {cat.get('name_en')}: {cat.get('score')}/100 ({cat.get('status', '').upper()})"
        c.drawString(margin + 8 * mm, state["y"], title)
        state["y"] -= LINE_H
        for issue in (cat.get("issues_en") or [])[:2]:
            para("• " + issue, font_size=9, indent_mm=14, italic=True)
    spacer(3)

    # ---------- 4. RECOMMENDED ACTIONS ----------
    section("4. Recommended actions / repair items")
    actions = verdict.get("actions", []) or []
    if not actions:
        para("No actions required — drone is operating normally.", font_size=9.5, indent_mm=4)
    else:
        for i, a in enumerate(actions, 1):
            para(f"{i}. {a.get('en', '')}", font_size=9.5, indent_mm=4)
    spacer(3)

    # ---------- 5. CLAIM ----------
    section("5. Claim / declaration")
    row("Claimed amount (BDT)", str(claim.get("claim_amount_bdt", "TBD")))
    spacer(4)
    para("I declare the above information is accurate and the log file is the original.",
         font_size=9, indent_mm=4)
    spacer(8)
    need(15 * mm)
    c.setStrokeColor(COL_TEXT)
    c.line(margin + 4, state["y"], margin + 70 * mm, state["y"])
    state["y"] -= 4 * mm
    c.setFillColor(COL_MUTED)
    c.setFont("Helvetica", 8.5)
    c.drawString(margin + 4, state["y"], "Operator signature & date")

    footer()
    c.save()
    return buf.getvalue()
