"""
LogIQ — Pilot logbook PDF.

Aviation-style pilot logbook export with all flights, totals, and a
declaration block for license renewal / CAAB submission.
"""
from __future__ import annotations

from io import BytesIO
from datetime import datetime
from typing import Iterable

from reportlab.lib import colors
from reportlab.lib.pagesizes import landscape, A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas


def build_logbook_pdf(pilot_name: str, flights: list[dict], total_hours: float, period: str = "") -> bytes:
    """flights: list of {date, file_name, airframe, duration_s, anomaly_score, label}."""
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=landscape(A4))
    W, H = landscape(A4)
    margin = 14 * mm

    def header(page_num: int):
        c.setFillColor(colors.HexColor("#1e3a8a"))
        c.rect(0, H - 22 * mm, W, 22 * mm, fill=1, stroke=0)
        c.setFillColor(colors.white)
        c.setFont("Helvetica-Bold", 18)
        c.drawString(margin, H - 11 * mm, "Pilot Logbook")
        c.setFont("Helvetica", 9)
        c.drawString(margin, H - 16 * mm, f"Pilot: {pilot_name}     Period: {period or 'All time'}     Total: {total_hours:.1f} hours")
        c.drawRightString(W - margin, H - 11 * mm, f"Generated by LogIQ — {datetime.now().strftime('%Y-%m-%d')}")
        c.drawRightString(W - margin, H - 16 * mm, f"Page {page_num}")

    def col_header():
        c.setFillColor(colors.HexColor("#e5e7eb"))
        c.rect(margin, H - 30 * mm, W - 2 * margin, 8 * mm, fill=1, stroke=0)
        c.setFillColor(colors.HexColor("#1f2937"))
        c.setFont("Helvetica-Bold", 9)
        cols = [
            ("#", 0),
            ("Date", 14),
            ("Airframe", 50),
            ("File name", 90),
            ("Duration", 175),
            ("Health", 205),
            ("Tag", 230),
            ("Firmware", 265),
        ]
        for label, x_mm in cols:
            c.drawString(margin + x_mm * mm, H - 26 * mm, label)

    page = 1
    header(page)
    col_header()
    y = H - 35 * mm
    line_h = 5.5 * mm

    for i, f in enumerate(flights, 1):
        if y < margin + 15 * mm:
            c.showPage()
            page += 1
            header(page)
            col_header()
            y = H - 35 * mm
        c.setFillColor(colors.HexColor("#1f2937"))
        c.setFont("Helvetica", 8.5)
        c.drawString(margin + 0 * mm, y, str(i))
        c.drawString(margin + 14 * mm, y, (f.get("date") or "")[:10])
        c.drawString(margin + 50 * mm, y, (f.get("airframe") or "")[:18])
        name = f.get("file_name", "") or ""
        if len(name) > 32: name = name[:32] + "…"
        c.drawString(margin + 90 * mm, y, name)
        dur_s = f.get("duration_s") or 0
        c.drawString(margin + 175 * mm, y, f"{int(dur_s/60)}m {int(dur_s%60)}s")
        score = f.get("anomaly_score")
        c.drawString(margin + 205 * mm, y, "ANOM" if score and score >= 0.18 else "OK")
        c.drawString(margin + 230 * mm, y, (f.get("label") or "—")[:14])
        c.drawString(margin + 265 * mm, y, (f.get("firmware") or "")[:14])
        y -= line_h

    # Summary + declaration on a fresh page
    c.showPage()
    page += 1
    header(page)
    y = H - 40 * mm
    c.setFillColor(colors.HexColor("#1f2937"))
    c.setFont("Helvetica-Bold", 14)
    c.drawString(margin, y, "Summary")
    y -= 10 * mm
    c.setFont("Helvetica", 11)
    c.drawString(margin, y, f"Total flights: {len(flights)}"); y -= 6 * mm
    c.drawString(margin, y, f"Total airtime: {total_hours:.1f} hours"); y -= 6 * mm
    anomalies = sum(1 for f in flights if (f.get("anomaly_score") or 0) >= 0.18)
    c.drawString(margin, y, f"Anomalous flights: {anomalies}"); y -= 12 * mm

    c.setFont("Helvetica-Bold", 12)
    c.drawString(margin, y, "Declaration"); y -= 8 * mm
    c.setFont("Helvetica", 10)
    c.drawString(margin, y, "I certify that the entries above are accurate and complete to the best of my knowledge."); y -= 16 * mm
    c.setStrokeColor(colors.HexColor("#1f2937"))
    c.line(margin, y, margin + 80 * mm, y)
    c.line(margin + 100 * mm, y, margin + 170 * mm, y)
    y -= 4 * mm
    c.setFillColor(colors.HexColor("#6b7280"))
    c.setFont("Helvetica", 8.5)
    c.drawString(margin, y, "Pilot signature")
    c.drawString(margin + 100 * mm, y, "Date")

    c.save()
    return buf.getvalue()
